@@include('active-tab.js')
@@include('digital-counter.js')
@@include('slider.js')
@@include('slider-testimonials.js')
@@include('slider-blog.js')
@@include('init-map.js')
@@include('to-top-button.js')
@@include('switch-theme.js')